---

- name: "Install required packages DEBIAN"
  ansible.builtin.package:
    name: ["libcurl4-openssl-dev"]
    state: "present"
  when: ansible_os_family == 'Debian'

- name: "Install required packages RedHat"
  ansible.builtin.package:
    name: ["openssl-devel"]
    state: "present"
  when: ansible_os_family == 'RedHat'

- name: "Install required pip libraries"
  ansible.builtin.pip:
    name: ["cryptography ", "pyopenssl"]
    state: "latest"
    executable: "pip"